README.md

Added the .NET Rocks podcast under the .NET heading.

Add .NET Rocks podcast

---

README.md

Add programming throwdown podcast. -> http://www.programmingthrowdown.com/

Add programming throwdown podcast

---

README.md
pull_request_template.md

Hey! Neat idea 👍
This PR Adds a table of contents for easy navigation of categories.
---
The following don't apply as I'm not adding a podcast :)

Add table of contents

---

README.md

Added: Practical AI, RFC, JS Party, The React Podcast
Improved: The Changelog, Go Time

Add and improve Changelog network podcasts

---

README.md

- [+] Add podcasts in appropriate categories in ascending order of podcast name
- [+] If there is no matching category, add a new category to the list in ascending order of category name, and add it to the table of contents in the same order
- [+] Add a brief description of the podcast
- [+] Add the frequency of episodes (Check the list for examples)

Addition of PHP podcasts

---

README.md

Adds Full Stack Cast - disclaimer, I'm one of the organitzers of the conference but I honestly think there's value in the podcast.

Add Full Stack Cast

---

README.md

The provided url seems to be dead, I found https://elmtown.simplecast.fm/ but their twitter points to elmtown.github.io (which points to the simplecast.fm url)— my assumption is the github pages link is canonical.

Fix Elm Town url

---

DE.md
ES.md
README.md

I've added some awesome infosec podcasts to the list :) 

Add infosec podcasts

---

README.md

Add the Host information for all the podcasts in the .NET section.

Add Host information for the .NET section

---

README.md

Added a number of podcasts in the data management and data science categories

Added the data management category and some related podcasts

---

README.md

Remove the "si=" parameter from Spotify url.   The value seems to be some referral/tracker token of the user that created the link,  and unnecessary.  Something to consider adding to issue: https://github.com/rShetty/awesome-podcasts/issues/189
Wrap iTunes link in () and | to be consistent with the way most links are displayed.
note: BSD Now uses a different (better?) style for links.  Something to consider fixing or adopting.
Mostly cleanup edits.

Correct some feed urls

---

README.md

Heya 👋 ,
Friday Afternoon Deploy is a podcast about the culture and chaos of software engineering. Special thanks to @tyreldenison , @ckinsey , @aFraley and @hayfever for making the Podcast happen.

Add "Friday Afternoon Deploy"

---

README.md

feat: added React Roundup podcast underJavaScript > React.js

---

README.md

Add devMode.fm to Web Development podcasts

---

README.md

Hosts for Complete Developer Podcast were put under the Command Line Heroes podcast. I moved the host info for the former, and added the correct host for the latter.

Corrected host info on 2 podcasts

---

README.md

The pull request standardizes frequency terms.
"Weekly"/"Weekly Once"/"Once every week" to "Once a week"
"Monthly"/"Monthly Once"/"Once per month" to "Once a month"
"Monthly Twice"/"Twice per month" to "Twice a month"
"Fortnightly" to "Once a fortnight"
Retained customized frequencies such as "Weekly(ish)", "Every other week", and so on

Update frequency terms

---

README.md

si param unnecessary, and may contain tracking or id info.

Remove the si= param in spotify link

---

README.md

- ember was not in alphabetic order
- added node.js
- moved nodeup to the node.js section
This resolves issue #151

fix up the javascript section

---

DE.md

Added a German podcast that focuses on software architecture and is presented by a group of (somewhat) well known group of engineers (publishing articles in magazines, speaking at conventions etc.)

Added a German podcast

---

DE.md

Added a german .NET podcast to the new .NET category

added DevCouch a german .NET podcast

---

README.md

Moved the Developing Up podcast into the "Career" category, as it was incorrectly placed in the "Web Development" category.
IDE also removed un-needed spaces at the ends of lines.

Edit the Developing Up podcast.

---

TR.md

* Translate Turkish podcasts page(TR.md) to Turkish.
* Update runtimes and frequencies.
All other language pages(German, Portuguese, Portuguese, Russian and Spanish) are written in their language.
There is no point to create Turkish podcasts page in English because all podcasts under that page is Turkish.

Turkish Podcasts Page Translation

---

README.md

Add Django Chat podcast

---

README.md

Add Privacy Advisor Podcast to security section

---

README.md

Adding "Docplanner Tech Talks" to General Software.

Docplanner tech talks

---

README.md

Not only the link is broken for Rusty Spike, the podcast hasn't had any new episodes since July 2018.

Remove rusty spike

---

README.md

Added working link to Data Skeptic podcast

---

RU.md

Add DotNet & More and Solo on .NET podcasts (ru)

---

DE.md

Added Logbuch:Netzpolitik, Chaosradio & Datenschutz Podcast

Add 3 German podcasts to list

---

README.md

A link to french podcasts is missing in the readme

add French podcasts in the Readme

---

README.md

Added Spotify links for Django Chat and Django Riffs

Added Spotify links for the Django podcasts

---

README.md

see announcment at:
https://www.rubytapas.com/2021/09/17/rubytapas-is-getting-graceful/
some of the content is still available for free at https://graceful.dev but much of the content is behind a paywall and is more of a video training course than a podcast.

discontinued by the creator in 2021-09
