rShetty/awesome-podcasts

README.md

* [The Bike Shed](http://bikeshed.fm/)
* [Front End Happy Hour](http://frontendhappyhour.com/)
* [Coding Blocks](https://www.codingblocks.net/)
* [Developer Tea](https://spec.fm/podcasts/developer-tea)
* [Arrested DevOps](https://www.arresteddevops.com/)

Add some more podcasts

---

README.md

Added the ReasonML podcast: Reason Town

---

README.md

Added CppCast

---

README.md

Added Android Developers Backstage

---

README.md

Added Data Skeptic (https://dataskeptic.com/podcast) with description and frequency

Add Data Skeptic

---

README.md

Add Elixir Talk

---

README.md

Added Code podcast

---

README.md

Updated list of Android podcasts and add kotlin

---

README.md

Add data science podcast

---

README.md

update list of Ruby

---

README.md

Added 'Dads in Development' to 'Web development'

---

README.md

update General list

---

README.md

add Java Podcast

---

README.md

Add DataSkeptic and Linear Digressions to ML section

---

README.md

update .NET list

---

README.md

Added The InfoQ Podcast in General software section.

---

README.md

Update existing Python podcasts

---

README.md

Added Multiplex podcast

---

README.md

add the Accidental Engineer podcast

---

README.md

Added 'Coder Radio to the General Software section

---

README.md

Updating frequency and description for DotNetRocks

---

README.md

Added ms dev show

---

README.md

Add Angular category and "Adventures in Angular"

---

README.md

I haven't verified any of the below

Properly escape __init__ :)

---

README.md

Hey there!
We've started a new podcast about enterprise software, distributed systems, and computer history and we'd love to feature it here. This PR covers the addition, corresponding to the submission guidelines.
Thanks much!

Adds Five Nines of Downtime

---

README.md

Adding Corey Quinn's podcast to devops section

---

README.md

add defn podcast

---

README.md

Add FLOSS Weekly

---

README.md

Add Embedded.fm

---

README.md

The Elixir Fountain
Description: Podcasts for news & interviews from around the @Elixirlang Community
Frequency : Varies

The Elixir Fountain (Soundcloud) added

---

README.md

More swift podcasts

---

README.md

Add some iOS podcasts

---

README.md

Add Scalalaz podcast

---

README.md

Updating Coding Blocks Description and Frequency

---

README.md

- [ /] Add podcasts in appropriate categories in ascending order of podcast name
- [ /] Add a brief description of the podcast
- [ /] Add the frequency of episodes (Check the list for examples)

Add CaSE podcast.

---

README.md

This caused the rest of the page to be bold.

Fix missing <b> tag

---

README.md

Add Go Gab podcast

---

README.md

Adding the CoRecursive podcast to the Functional category of podcasts. One of my newest finds and one of the best I've heard out there :)

add the corecursive podcast

---

README.md

Added Complete Developer Podcast and Junior Developer Toolbox to General Software
- [X ] Add podcasts in appropriate categories in ascending order of podcast name
- [X ] If there is no matching category, add a new category to the list in ascending order of category name, and add it to the table of contents in the same order
- [X ] Add a brief description of the podcast
- [X ] Add the frequency of episodes (Check the list for examples)

Added two podcasts

---

README.md

update Syntax podcast

---

README.md

Add Vue.js JavaScript framework.

---

README.md

Added base.cs podcast to the general software category

---

README.md

Add Groovy Podcast

---

README.md

Add CodePen radio

---

README.md

Adding WeeklyDevTips

---

README.md

Add SANS ISC StormCast

---

README.md

Adding a new podcast that covers interesting software engineering related topics.
~Thanks

Added "Command Line Heroes"

---

README.md

Add Fireside Swift

---

README.md

Added "Merge Conflict" to .NET.

---

README.md

Add several podcasts

---

README.md

Hi, guys! 
I fixed markdown a bit:
1. Change HTML `<b>` on `**` markdowns bold syntax.
2. Change `-` unsorted list on `*`.
3. Fixed common layout for consistency.
I used [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint} for changing.
Let me know what you think.

Fix markdown layout

---

README.md

Add two more podcasts

---

README.md

Add Devops Cafe podcast

---

README.md

Adding R podcast

---

README.md

All pre-checks should be set to go.

Adding Greater than Code to the list

---

README.md

https://github.com/rShetty/awesome-podcasts/issues/29

add phpugly podcast, add php category

---

README.md

update machine learning guide

---

README.md

https://github.com/rShetty/awesome-podcasts/issues/75

Add Cyber wire and Darknet Diaries

---

README.md

https://github.com/rShetty/awesome-podcasts/issues/80

add Chance the dev

---

README.md

5 minutes of React podcast - Podcast about React hot topics and JavaScript ecosystem.
https://5minreact.audio/

Add "5 minutes of React podcast"

---

README.md
TR.md

Here are the changes I have made 
- There was duplicated podcasts on the list. I have removed them. 
- And added languages of all podcasts. 
- There are great podcasts that I'm listening in Turkish. I have added them to the list.

Added TR.md file for Turkish podcasts and removed duplicated links from README.md

---

RU.md

Add "Пятиминутка PHP" and "Пятиминутка React" podcasts

---

README.md

skat00sh-ai/ml-list-update

---

contributing.md

To add contribution guidelines

---

README.md

Update README.md - add Indielixer

---

README.md

Add "Views on View" podcast (https://devchat.tv/views-on-vue/).

Add "Views on Vue" podcast

---

README.md

Add BookBytes

---

README.md

- Add AFK and Founders Talk
- Set runtime for Practical AI
- Update description of The Changelog
- Fix title for Go Time
- Change React Podcast address

Update Changelog podcasts

---

README.md

Add More Than Just Code podcast

---

README.md

Add ThoughtWorks podcast

---

README.md

Added the Test and Code podcast :)

Added Test and Code podcast

---

.github/pull_request_template.md

Copied directly from contributing.md

Add runtime checkbox to pull request template

---

README.md

Add Cpp.chat

---

README.md

3 New Podcasts

---

README.md

Adding Stacktrace as an iOS podcast

---

README.md

Add language description on DevNaEstrada podcast

---

README.md

Add "The Ruby Testing Podcast"

---

TR.md

Adding 2 new Turkish podcast source to TR.md

---

README.md

Added Swift over Coffee

---

README.md

Added The Swift Community Podcast

---

README.md

Add devpath.fm

---

README.md

This show has a short show every Monday and a longer one on Wednesday.

Fixed Syntax podcast Frequency

---

README.md

Before raising a PR and it getting merged, ~make sure you~ **I** have completed the following:
- [**OK**] Add podcasts in appropriate categories in ascending order of podcast name
- [**NA**] If there is no matching category, add a new category to the list in ascending order of category name, and add it to the table of contents in the same order
- [**OK**] Add a brief description of the podcast
- [**OK**] Add the frequency of episodes (Check the list for examples)
- [**OK**] Add the runtime of episodes, giving an approximate range and an average duration.
Thanks for ~your~ **accepting** contributions and being awesome :) Cheers.

Add the Rust podcast "Request for Explanation"

---

README.md

Adding the EmberMap podcast

---

README.md

Adding the excellent Darknet Diaries from Jack Rhysider.

Add Darknet Diaries to English list

---

README.md

Hi I've added Software testing category and two podcasts there.
- [ X] Add podcasts in appropriate categories in ascending order of podcast name
- [ X] If there is no matching category, add a new category to the list in ascending order of category name, and add it to the table of contents in the same order
- [X ] Add a brief description of the podcast
- [ X] Add the frequency of episodes (Check the list for examples)
- [ X] Add the runtime of episodes, giving an approximate range and an average duration.

Mwyrodek testing podcast

---

README.md

Under the Radar changed their frequency

updated under the radar frequency

---

README.md

Nothing too complex here :-) 
- [✔️ ] Add podcasts in appropriate categories in ascending order of podcast name
- [✔️ ] If there is no matching category, add a new category to the list in ascending order of category name, and add it to the table of contents in the same order
- [✔️ ] Add a brief description of the podcast
- [ ✔️] Add the frequency of episodes (Check the list for examples)
- [✔️ ] Add the runtime of episodes, giving an approximate range and an average duration.

Adding Linux Uplugged, Linux Action News, and refactoring BSD Now.

---

README.md

Added It's All Widgets! Flutter Podcast and Flutter section

Flutter changes

---

README.md

Hi, I add Laravel News Podcast and put it in sub-category PHP > Laravel.

Add laravel news podcast

---

README.md

Adds The Drunken UX Podcast under the Web Development category

---

DE.md
README.md

I added translations and fixed a small typo

small changes

---

README.md

https://artofproductpodcast.com/

Add Art of Product podcast

---

PT.md
README.md

- [X ] Add podcasts in appropriate categories in ascending order of podcast name
- [ X] If there is no matching category, add a new category to the list in ascending order of category name, and add it to the table of contents in the same order
- [ X] Add a brief description of the podcast
- [ X] Add the frequency of episodes (Check the list for examples)

Add new podcast and removed duplicate entries

---

README.md

Hi,
I would like to add some podcasts and channels related to [Ionic](http://ionicframework.com).
Thx for the great list of podcasts 👍 
David

Add Ionic podcasts and channels

---

README.md

Add functional programming show Elixir Mix

---

README.md

New Podcast: Late Night Linux

---

README.md

I have followed the steps below.

Add Eat Sleep Code

---

pt_PT.md

Adding Portuguese of Portugal podcasts list to awesome-podcasts

---

DE.md

Added agile "scrumkaputt" podcast

---

README.md

Add The Frontside Podcast

---

README.md

add iteration

---

README.md

Update the podcast Host field for Agile and Android sections

Update the podcast Host field for Agile and Android sections

---

README.md

for sections c++, career, clojure, community/inspiration

Update podcast host information for 'c' sections

---

README.md

Added Code Cast ZM 

---

README.md

https://twitter.com/minWi/status/1092737776146149376:
> @KubernetesPod I don't see you here! github.com/rShetty/awesom…
You do now!
- Added new category and put it in the right place (and in the ToC)
- Added description, frequency, hosts and runtime
Thanks!

Add Kubernetes/Cloud Native section and Kubernetes Podcast

---

README.md

Added Productivity in Tech, The .NET Core Podcast, and Troy Hunt's Weekly Update

---

ES.md

* [Sin Humo Podcast](https://anchor.fm/sin-humo)
* **Descripción**: Un Podcast sobre programación y tecnología. Libre de humo. De la mano de [@esacrosa](https://twitter.com/esacrosa) y [@fernandezpablo](https://twitter.com/fernandezpablo)
* **Frecuencia**: No definida.
* **Duración**: 45 - 90 min
---
* [Sin Humo Podcast](https://anchor.fm/sin-humo)
* **Description**: A Podcast about programming and technology. Smoke free. By [@esacrosa](https://twitter.com/esacrosa) and [@fernandezpablo](https://twitter.com/fernandezpablo)
* **Frequency**: Not defined.
* **Duration**: 45 - 90 min

[es] Add "Sin humo"

---

README.md

Some entries had a  space before the colon, but most do not.
Remove the space in those entries.
just edits...🖊 

fix inconsistent formatting of entries

---

DE.md

Update DE.md - Added Codestammtisch

---

README.md

Correct spelling errors

---

README.md

To keep bullet points consistent, I have removed an extra and unneeded bullet point from the Linux section.

Cleanup: Remove extra bullet point

---

README.md

Add Developer Melange

---

README.md

Added new testing podcast basing on this ranking 
https://blog.feedspot.com/software_testing_podcasts/ - podcast that had Podcast with no new episodes in last 3 month weren't taken into account.

more testing podcast

---

README.md

Add While True Talk podcast

---

ES.md

Adding two new podcasts, one new category and fixing the order of existing podcasts.

---

PT.md

Add a first entry and a new section about Data Science/Machine Learning podcasts.

Add Pizza de Dados and Data Science section in PT

---

README.md

- [ x] Add podcasts in appropriate categories in ascending order of podcast name
- [ x] If there is no matching category, add a new category to the list in ascending order of category name, and add it to the table of contents in the same order
- [ x] Add a brief description of the podcast
- [ x] Add the frequency of episodes (Check the list for examples)
- [ x] Add the runtime of episodes, giving an approximate range and an average duration.

Added DevJourney Podcast

---

README.md
contributing.md

fixups
add space after :
remove spotify si= param
add twitter link

corrections to Fri Aft Deploy

---

contributing.md

update contributing.md template:
- add a request to add the host information
-  remove period character to be consistent with other bullet points

Add request for host to contributing template

---

.github/pull_request_template.md

in #225, forgot to add host request to the PR template

Add request for host to pull request template

---

README.md

Add new podcast from the source

---

PT.md

Added LinuxTips podcast

---

README.md

Add The Tech Guy podcast

---

RU.md

Added web-standarts podcast

---

README.md

fix the alphabetical order of a section.
Swift appeared before Software Testing, but should appear after.

fix ordering - Swift was before Software Testing

---

README.md

Add tech stuff podcast

---

README.md

Added Kernel Panic podcast

---

README.md

Added list of supported languages.

---

README.md

added codenewbie and learn to code with me

---

DE.md

Add repod.at podcast

---

README.md

Added EmacsCast.

---

README.md

This PR:
* Updates the host for the Software Engineering Daily podcast
* Adds a link to podcast episode page for the same (instead of a link to the home page)
* Fixes a few minor grammar errors

Update details & fix grammar

---

README.md

Add Remote Ruby Podcast to Ruby/Rails category

add Remote Ruby Podcast

---

DE.md

Fix indentation

---

README.md

Added The REPL.

---

RU.md

Add "Make it sexy" (frontsexy) podcast

---

ES.md

Add Detrás del Pixel Podcast

---

PT.md

Adding br podcasts

---

README.md

Add Tech Queens Podcast 👑

---

README.md

Sorry - I missed adding brackets in my first PR.

Added brackets

---

README.md

Updated John Jacob's twitter handle

Updated John Jacob's twitter handle

---

TR.md

Added 1 new Turkish podcast source to TR.md

---

README.md

Adding two missing colons

---

README.md

Added new podcasts:
Adventuring in DevOps
Choose Linux
Destination Linux
Linux Headlines
Open Source Security Podcast
Ubuntu Security Podcast

Adding new podcasts

---

README.md

added java podcast

---

README.md

Adding Jessica Rose's awesome podcast

Add Pursuit Podcast

---

PT.md

Nova sessão: carreira 

---

README.md

Add Data Viz Today in DS/ML section

---

README.md

Added Developing Up podcast

---

README.md

I add `The Laracasts Snippet` podcast by Jeffrey Way

add the laracasts snippet podcast

---

README.md

The newest pod from Changelog ✌️

Add Brain Science podcast

---

PT.md

Add Quebradev Podcast

---

TR.md

added more details about Paraşüt'le Üretim Bandı

---

README.md

Add "Are We Podcast Yet?" Rust podcast

---

README.md

feat(kubernetes): add 3 new kubernetes podcasts

---

README.md

Added my own podcast - Inspect

---

README.md

Add the Programming podcast

---

pt_PT.md

Add PseudoCódigo podcast to pt_PT

---

README.md

Added Rushing Forward

---

README.md

Add Rustacean Station

---

README.md

Feel free to listen to the Podcast before merging, but we'd be honored to be among this list.

Add Namespace Podcast

---

README.md

Adding The Front End Podcast to the list under Web Development
All the things have been done!

Adds The Front End Podcast

---

FR.md

Added FR Tech podcast

---

FR.md

formatting alignment

---

FR.md

correct indent

---

README.md

Added Real World Serverless podcast.

---

README.md

Add State of the Hack to Security section

---

README.md

Add Humans of InfoSec to Security section

---

README.md

Thanks for Maintaining this Awesome list!
I recently started listening to a great new-ish Vue podcast with panel of hosts who used to be on Views on Vue.

Added Enjoy the Vue podcast to Vue.JS section

---

DE.md

Add security section and Unter4Ohren in DE list

---

README.md

Add 7 Minute Security to security section

---

README.md

Add privacy, security and OSINT show to security

---

README.md

Add Detections security podcast

---

README.md

Add Cyber Security Sauna to security section

---

README.md

Adding BarCoding podcast

---

DE.md
README.md

Added two podcasts: Software Defined Talk, Netzpolitik

---

README.md

Matt Stauffer has resumed making the Laravel Podcast and the content is high quality.

adding The Laravel Podcast

---

RU.md

added "Android Dev Podcast" and "Flutter Dev Podcast"

---

README.md

added The Real Python Podcast

---

README.md

3 New iOS Podcasts

---

DE.md

Added INNOQ podcast

---

RU.md

Added "Android Broadcast" podcast

---

ES.md

add new podcast in spanish (development and programming)

---

README.md

Add Software Engineering Unlocked

---

README.md

Added `Stories From the Workshop` to Community/Inspiration section.

Added podcast to Community/Inspiration section.

---

PT.md

Added "Laravel Portugal Live" portuguese podcast

#hacktobefest Added "Laravel Portugal Live" portuguese podcast

---

README.md

- Added a new section for DevRel and a podcast for a DevRel Podcast which I Host.

[NEW] Topic and Category section

---

ES.md

add polémica en /var

---

README.md

Updated the description, https & frequency

Updated the infos of the DevJourney Podcast

---

README.md
TR.md

Tr update and djangorifss podcast add

---

README.md

Add Working Code podcast

---

RU.md

Add RadioDotNet podcast (ru)

---

README.md

Add The Data Engineering Show podcast

---

DE.md

Add binaergewitter

---

README.md

Add MongoDB Podcast

---

FR.md

- [] Add the frequency of episodes (check the list for examples)
- [] Add the runtime of episodes, giving an approximate range and an average duration

add podcast Les Cast Codeurs

---

FR.md

Add Dev Café Podcast

---

ES.md

Found an error in 2 Spanish podcasts, with crossed data between them.
Fixed the hosts and added a proper description in one of them

[ES] Fix 2 spanish podcasts, crossed data

---

README.md

Thanks for this repo. I wanted to add a great developer who helped me a lot during my programming journey.

Add a podcast in Readme.md file
